baseURL = "https://example.com/"
languageCode = "en-us"
title = "Essential Math for Artificial Intelligence"
# theme = "hextra"
theme = "hugo-PaperMod"

[params]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    noClasses = false



